name: Issue Labeler
on:
  issues:
    types: [ opened ]
jobs:
  label-issue-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Parse issue form
        uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/UPDATED-BUG-FORM.yml

      - name: Set labels based on issue_type field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v1
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: issue_type
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set labels based on priority field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v1
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: priority
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set labels based on components
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v1
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: components
          token: ${{ secrets.GITHUB_TOKEN }}

